name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/386,linux/amd64,linux/arm64
          push: true
          build-args: |
            "VERSION=${{ github.ref }}"
          tags: |
            ghcr.io/${{ github.actor }}/distress:latest
            ghcr.io/${{ github.actor }}/distress:${{ github.ref_name }}
